version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./nginx:/etc/nginx
    networks:
      - bridge
    depends_on:
      - nats
      - user
      - log
  nats:
    image: nats-streaming:alpine
    command: [
      "-p", 
      "4222", 
      "-m", 
      "8222", 
      "-hbi", 
      "5s", 
      "-hbt", 
      "5s", 
      "-hbf", 
      "2", 
      "-SD", 
      "-cid", 
      "courseware"
    ]
    ports:
      - 4222
      - 8222
    networks:
      - bridge
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - bridge
  user:
    image: gdvn/courseware-user
    build: 
      context: ./src/user
      secrets:
        - npmrc
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI_USER_SRV}
      - NATS_URL=http://nats:4222
      - NATS_CLIENT_ID=user-srv
      - NATS_CLUSTER_ID=courseware
      - REDIS_URI=redis://cache:6379
    volumes:
      - ./src/user:/usr/app:rw
    networks:
      - bridge
    depends_on:
      - nats
      - cache
  course:
    image: gdvn/courseware-course
    build: 
      context: ./src/course
      secrets:
        - npmrc
    ports:
      - 3001:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI_COURSE_SRV}
      - NATS_URL=http://nats:4222
      - NATS_CLIENT_ID=course-srv
      - NATS_CLUSTER_ID=courseware
    volumes:
      - ./src/course:/usr/app:rw
    networks:
      - bridge
    depends_on:
      - nats
  log:
    image: gdvn/courseware-log
    build: 
      context: ./src/log
      secrets:
        - npmrc
    ports:
      - 3002:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI_LOG_SRV}
      - NATS_URL=http://nats:4222
      - NATS_CLIENT_ID=log-srv
      - NATS_CLUSTER_ID=courseware
    volumes:
      - ./src/log:/usr/app:rw
    networks:
      - bridge
    depends_on:
      - nats

secrets:
  npmrc:
    file: .npmrc

networks:
  bridge: