apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-sys-srv-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: srv-user
          image: micro-system/user
          env:
            - name: MONGO_URI
              value: "mongodb://db-user:27017/user"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://ebus-nats:4222"
            - name: NATS_CLUSTER_ID
              value: microservices
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
